name: NPM publish force (from package)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install, build, and test
      run: |
        npm install -g npm
        npm ci
        npm run bootstrap:ci
        npm run build
        npm test
      env:
        CI: true
    - name: lerna publish
      run: |
        lerna publish from-package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
