name: NPM/Lerna version - patch and publish

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: npm install, build, and test
      run: |
        npm install -g npm
        npm ci
        npm run bootstrap:ci
        npm run build
        npm test
      env:
        CI: true
    - name: create patch version
      run: |
        npm run version:patch
    - name: commit and tag version
      run: |
        git commit
        git push
        git push --tags
    - name: publish version
      run: |
        npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
